apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_deployment
spec:
  selector:
    matchLabels:
      run: test_deployment
  replicas: 3
  template:
    metadata:
      labels:
        run: test_deployment
    spec:
      containers:
        - name: test_deployment
          image: $IMAGE
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test_deployment
spec:
  selector:
    run: test_deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080